name: rebuild-snippets

on:
  # Whenever there is a new `ditto` release and, with it, an update of the `releases.json` file.
  repository_dispatch:
    types: ['new-ditto-release']
  workflow_dispatch:

jobs:
  create-pull-request:
    name: Update snippets 
    runs-on: ubuntu-latest
    environment: rebuild-snippets
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAT }}
      - name: Checkout ditto repository
        uses: actions/checkout@v3
        with:
          repository: getditto/ditto
          token: ${{ secrets.GH_PAT }} 
          path: ditto
      - name: wget
        uses: wei/wget@v1
        with:
          args: -qO- https://software.ditto.live/releases/snippets.json > snippets.json
      - name: "Add snippets" 
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          npm i 
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git add snippets.json
          git commit -m "Update snippets from latest ditto release" 
      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Updating snippets from latest ditto release"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "okdistribute"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
